// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('home', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('home', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1309, height: 823 })
    await driver.findElement(By.id("headerText")).click()
    await driver.findElement(By.css("li:nth-child(1) .long:nth-child(3)")).click()
    await driver.findElement(By.css(".PatientInfo-div > h1")).click()
    await driver.findElement(By.css(".PatientTimeLine-div > h1")).click()
  })
})
